### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by palo** [thirtybees/tbgdpr#2]
Steps to reproduce:

```
cd path/to/shop/modules/
git clone git@github.com:thirtybees/tbgdpr.git
cd tbgdpr
composer install
```
Then go to back office -> Modules & Services, search for tbgdpr and click 'Install'.

Result:

```
[ThirtyBeesException]
Class 'TbGdprModule\PhpParser\ParserFactory' not found
at line 152 in file modules/tbgdpr/traits/Installation.php
```

**Comment by Traumflug** [comment]
I should have mentioned this when closing issue #1: one has to build the module before packaging or using it.

    cd tbgdpr
    ./build.sh

**Comment by palo** [comment]
Thanks for helping @Traumflug  
Build isn't working in my windows 10. 
Ubuntu 16 goes a little further, but i think this this error is preventing a successful build.
``PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in phar:///home/dev/tbgdpr-master/php-scoper.phar/src/Console/Application.php on line 18
``
A zip file is created, i can import the module but install fails with the same error as before.
```
[ThirtyBeesException]
Class 'TbGdprModule\PhpParser\ParserFactory' not found
at line 152 in file modules/tbgdpr/traits/Installation.php
```
If i comment the offending function in modules/tbgdpr/traits/Installation.php, it installs but i get this error when i try to configure the module.
```
Call to undefined function dot()
at line 273 in file modules/tbgdpr/tbgdpr.php

271.             'anonymous' => [
272.                 [
273.                     'name'  => dot($this->getRightToBeAnonymousForm())->get('form.legend.title'),
274.                     'icon'  => dot($this->getRightToBeAnonymousForm())->get('form.legend.icon'),
275.                     'value' => $this->displayRightToBeAnonymousForm(),
276.                     'badge' => '',
277.                 ],
```

**Comment by snowycatsoftware** [comment]
@palo,

I just ran the build.sh script using npm + webpack. The module installs without any problems. I have added the .zip in this comment, so you can try.

Regards

[tbgdpr-v1.0.0.zip](https://github.com/thirtybees/tbgdpr/files/2123236/tbgdpr-v1.0.0.zip)

**Comment by palo** [comment]
Thank you @snowycatsoftware  
It installs perfectly.
