### ISSUE TITLE
4 years later still unable to install

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/tbgdpr#4]
Fatal Error: require_once(): Failed opening required '/home/11111/public_html/domain.com/modules/tbgdpr/vendor/autoload.php' (include_path='/home/11111/public_html/domain.com/vendor/pear/archive_tar:/home/11111/public_html/domain.com/vendor/pear/console_getopt:/home/11111/public_html/domain.com/vendor/pear/pear-core-minimal/src:/home/11111/public_html/domain.com/vendor/pear/pear_exception:.:/opt/alt/php74/usr/share/pear')

modules/tbgdpr/tbgdpr.php line 24

and

require_once(/home/11111/public_html/domain.com/modules/tbgdpr/vendor/autoload.php): failed to open stream: No such file or directory

modules/tbgdpr/tbgdpr.php line 24

and

Array and string offset access syntax with curly braces is deprecated

modules/tbgdpr/tbgdpr.php line 805

EDIT:...... oh I have to build it.... :/

**Comment by getdatakick** [comment]
There is no official released zip file for this module. If you downloaded source code, you have to build it yourself

**Comment by therampagerado** [comment]
Yes, just saw that...

I'm an idiot... :D

**Comment by getdatakick** [comment]
To be honest, I don't think this module was ever finished. You could give it a try, and report what is missing. Maybe if we know where we are, we can go forward :)
